import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/providers/query-provider";
import { CartProvider } from "@/providers/cart-provider";
import { SessionProvider } from "next-auth/react";
import { DeliveryProvider } from "@/providers/deliveryFeeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body>
        <SessionProvider>
          {" "}
          <QueryProvider>
            <DeliveryProvider>
              <CartProvider>
                {children}

                <Toaster
                  position="top-center"
                  reverseOrder={false}
                  gutter={8}
                  toastOptions={{
                    duration: 3000,
                  }}
                />
              </CartProvider>
            </DeliveryProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
